# Generated by Django 3.1.5 on 2021-01-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['author', 'title']},
        ),
    ]
